services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-docker
    user: root
    privileged: true
    environment:
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=C.UTF-8
      - JENKINS_HOME=/var/jenkins_home
      - JENKINS_SLAVE_AGENT_PORT=50000
      - REF=/usr/share/jenkins/ref
      - JENKINS_VERSION=2.464
      - JENKINS_UC=https://updates.jenkins.io
      - JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
      - JENKINS_INCREMENTALS_REPO_MIRROR=https://repo.jenkins-ci.org/incrementals
      - COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
      - JAVA_HOME=/opt/java/openjdk
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/var/jenkins_home/backups
    networks:
      - jenkins_network

  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pactbroker:
    image: pactfoundation/pact-broker
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_PORT: '9292'
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      PACT_BROKER_WEBHOOK_HTTP_METHOD_WHITELIST: POST GET PUT PATCH DELETE
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: /.*/
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      PACT_BROKER_BASE_URL: 'https://localhost http://localhost http://localhost:9292 http://pact-broker:9292 https://host.docker.internal http://host.docker.internal http://host.docker.internal:9292'

volumes:
  pactbroker_data:
  jenkins_home:
  postgres-volume:

networks:
  jenkins-net:
  jenkins_network:
    driver: bridge
